require('dotenv').config()
const express = require('express')
const bodyParser = require('body-parser')
const handle404Error = require('./src/middlewares/handle404Error')
const app = express()

const itemRoute = require('./src/routes/item.route.js')
const usuariosRoute = require('./src/routes/usuario.router.js')
const entradaRoute = require('./src/routes/entrada.route')
const saidaRoute = require('./src/routes/saida.route')
const itemReportRoute = require('./src/routes/item-report.route')
const fornecedorRoute = require('./src/routes/fornecedor.route')
const handleError = require('./src/middlewares/handleError')

app.use(bodyParser.urlencoded({ extended: true }))
app.use(bodyParser.json())
app.use('/api/usuarios', usuariosRoute)
app.use('/api/itens', itemRoute)
app.use('/api/entradas', entradaRoute)
app.use('/api/saidas', saidaRoute)
app.use('/api/item-report', itemReportRoute)
app.use('/api/fornecedores', fornecedorRoute)
app.use(handle404Error)
app.use(handleError)

app.listen(process.env.PORTA, () => {
    console.log('Conectado!')
})